// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file exa/bug_checker_pb/bug_checker.proto (package exa.bug_checker_pb, syntax proto3)
/* eslint-disable */
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
/**
 * Describes the file exa/bug_checker_pb/bug_checker.proto.
 */
export const file_exa_bug_checker_pb_bug_checker = /*@__PURE__*/ fileDesc("CiRleGEvYnVnX2NoZWNrZXJfcGIvYnVnX2NoZWNrZXIucHJvdG8SEmV4YS5idWdfY2hlY2tlcl9wYiInCgNGaXgSDwoHb2xkX3N0chgBIAEoCRIPCgduZXdfc3RyGAIgASgJItMBCgNCdWcSCgoCaWQYASABKAkSDAoEZmlsZRgCIAEoCRINCgVzdGFydBgDIAEoBRILCgNlbmQYBCABKAUSDQoFdGl0bGUYBSABKAkSEwoLZGVzY3JpcHRpb24YBiABKAkSEAoIc2V2ZXJpdHkYByABKAkSEgoKcmVzb2x1dGlvbhgIIAEoCRISCgpjb25maWRlbmNlGAkgASgBEhIKCmNhdGVnb3JpZXMYCiADKAkSJAoDZml4GAsgASgLMhcuZXhhLmJ1Z19jaGVja2VyX3BiLkZpeGIGcHJvdG8z");
/**
 * Describes the message exa.bug_checker_pb.Fix.
 * Use `create(FixSchema)` to create a new message.
 */
export const FixSchema = /*@__PURE__*/ messageDesc(file_exa_bug_checker_pb_bug_checker, 0);
/**
 * Describes the message exa.bug_checker_pb.Bug.
 * Use `create(BugSchema)` to create a new message.
 */
export const BugSchema = /*@__PURE__*/ messageDesc(file_exa_bug_checker_pb_bug_checker, 1);
