providers:
  9router:
    baseUrl: https://sunta-api.up.railway.app/v1
    apiKey: YOUR_API_KEY_HERE
    authHeader: true
    api: openai-completions
    models:
      - id: SWE-Pickle
        name: SWE-Pickle
        reasoning: true
        input: [text]
        contextWindow: 200000
        maxTokens: 64000
        cost:
          input: 0
          output: 0
          cacheRead: 0
          cacheWrite: 0

      - id: ChatGPT-Codex
        name: ChatGPT-Codex
        reasoning: true
        input: [text, image]
        contextWindow: 256000
        maxTokens: 64000
        cost:
          input: 0
          output: 0
          cacheRead: 0
          cacheWrite: 0

      - id: ChatGPT-OSS
        name: ChatGPT-OSS
        reasoning: true
        input: [text]
        contextWindow: 128000
        maxTokens: 64000
        cost:
          input: 0
          output: 0
          cacheRead: 0
          cacheWrite: 0

      - id: Claude-Sonnet
        name: Claude-Sonnet
        reasoning: true
        input: [text, image]
        contextWindow: 256000
        maxTokens: 64000
        cost:
          input: 0
          output: 0
          cacheRead: 0
          cacheWrite: 0

      - id: Claude-Opus
        name: Claude-Opus
        reasoning: true
        input: [text, image]
        contextWindow: 256000
        maxTokens: 64000
        cost:
          input: 0
          output: 0
          cacheRead: 0
          cacheWrite: 0
      - id: XiaoMi-Mimo
        name: XiaoMi-Mimo
        reasoning: true
        input: [text, image]
        contextWindow: 384000
        maxTokens: 64000
        cost:
          input: 0
          output: 0
          cacheRead: 0
          cacheWrite: 0

      - id: Auto
        name: Auto
        reasoning: true
        input: [text]
        contextWindow: 200000
        maxTokens: 64000
        cost:
          input: 0
          output: 0
          cacheRead: 0
          cacheWrite: 0

      - id: CLAUDE
        name: CLAUDE
        reasoning: true
        input: [text, image]
        contextWindow: 256000
        maxTokens: 64000
        cost:
          input: 0
          output: 0
          cacheRead: 0
          cacheWrite: 0

      - id: MiniMax-M3
        name: MiniMax-M3
        reasoning: true
        input: [text, image]
        contextWindow: 256000
        maxTokens: 64000
        cost:
          input: 0
          output: 0
          cacheRead: 0
          cacheWrite: 0

      - id: GeneralLM
        name: GeneralLM
        reasoning: true
        input: [text]
        contextWindow: 200000
        maxTokens: 64000
        cost:
          input: 0
          output: 0
          cacheRead: 0
          cacheWrite: 0